### ISSUE TITLE
[Android] Icons are not displayed in release-build

### ISSUE THREAD

**Issue by danielang** [prscX/react-native-popover-menu#11]
Hello @prscX 
In the release-build of my app the icons of the popover component are not displayed.
It works fine on iOS and Android-debug-build.

**Comment by prscX** [comment]
Thanks @danielang for raising the issue.

My bad, I have never checked this on release build. I can understand the priority of this issue, please give me some time I will test and resolve the same.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @danielang,

I have done a detailed research but I am not able to find the right solution for this issue. Basically in native we receive image url which is working as excepted in debug mode but on production it is not generating the right output.

One of the possible workaround I am thinking is to migrate to [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). Doing this we will only be able to show icons provided by this library. Please let me know your views for the same.

Thanks
Pranav

**Comment by danielang** [comment]
Hey @prscX 
Thank you for the fixes and your commitment and sorry for my late response. I was pretty busy the last weeks.

I think their must be a solution for this issue. Perhapse we have to check how the Image-Component does the loading of an image in a production build.
react-native-vector-icons is a possibility, BUT it will limit this library and creates additional dependencies.

**Comment by prscX** [comment]
Hi @danielang,

Completely agree with your views. May be we can enable/support both ways of providing icons. For quick workaround I can enable support for `react-native-vector-icons` and going forward based on R&D we can fix the issue.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @danielang , I have enabled the support for [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), now you will be able to integrate and use their icons. Please follow `README` in order to use the same. 

Can you please install latest version and verify the same. Please let me know in case you face any issues.

Thanks
Pranav
