### ISSUE TITLE
[ios] last item border should not be visible

### ISSUE THREAD

**Issue by petrkrizek** [prscX/react-native-popover-menu#13]
On iOS, the last item has bottom border, it should not be there.

![border-bug](https://user-images.githubusercontent.com/37615991/39755664-0994bfee-52c7-11e8-852a-419435a2ca27.jpg)

**Comment by petrkrizek** [comment]
@prscX any update? :) Thanks

**Comment by prscX** [comment]
Hi @petrkrizek,

I have migrated iOS native library from [liufengting/FTPopMenu](https://github.com/liufengting/FTPopMenu) to [liufengting/FTPopOverMenu](https://github.com/liufengting/FTPopOverMenu) for better API's. Can you please install latest library and verify the same.

Please follow `README` for the installation steps. Let me know in case you still face the same issue.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @petrkrizek, I have verified and is working as expected post upgrading the library version. 

For now I am closing this issue. Let me know if you face any issues.

Thanks
</ Pranav >
