### ISSUE TITLE
App crashes when using the icon prop

### ISSUE THREAD

**Issue by Cassendra4** [prscX/react-native-popover-menu#21]
When I call RNPopoverMenu.Show() my app crashes. I can't understand why. But this happens if I use the "icon" prop. I guess this is something with the 'family' prop. 

Versions:
 "react-native-vector-icons": "4.5.0",
"react-native-popover-menu": "0.0.18",

Here is my code:

```
import Icon2 from 'react-native-vector-icons/MaterialCommunityIcons';
  import Icon from 'react-native-vector-icons'

```
 ```
<TouchableOpacity
                            ref={ref => {
                                this.ref = ref;
                            }}
                                onPress={() => {this.renderMenu(this.ref)}}
                               >
                            <Icon2 name='dots-vertical' size={30} color={Colors.textWhite}/>
                        </TouchableOpacity>
```

```
 renderMenu = (ref) => {
       let remove = <Icon family={'Feather'} name='user-minus' size={30} color={Colors.textWhite}/>;
        let block = <Icon family={'MaterialIcons'} name='block' size={30} color={Colors.textWhite}/>;
        let menus = [
            {
                menus: [
                    { label: "Remove", icon: remove},
                    { label: "Block"}
                ]
            },
        ];

        RNPopoverMenu.Show(ref, {
            menus: menus,
            onDone: (sectionSelection, menuSelection) => {  console.log("selected item index: " + menuSelection)},
            onCancel: () => { console.log("popover canceled")}
        });
    };
```

**Comment by prscX** [comment]
Thanks @Cassendra4 for raising the issues.

Is icon rendered on the screen?

Thanks 
</ Pranav >

**Comment by Cassendra4** [comment]
No, Actually I can't see anything rendering related to the menu because when I call RNPopoverMenu.Show() the app crashes. But if I remove the "icon" prop and re-render, then of course the menu renders fine with labels

**Comment by prscX** [comment]
@Cassendra4: I believe the `RNVector -> MaterialCommunityIcons` is not properly configured to your iOS app. 

Can you please try by rendering the same icon on the app screen apart from menu. If it renders then it should render here as well. Please share your findings.

Thanks
</ Pranav >

**Comment by Cassendra4** [comment]
Hi, I actually tried this on Android. This import
`import Icon2 from 'react-native-vector-icons/MaterialCommunityIcons';` works fine with all the other places. I used it just to add a button as shown in the figure below.

![screenshot_1533632162](https://user-images.githubusercontent.com/8186992/43765721-3e139582-9a4e-11e8-9a1b-fddf5ca85ffb.png)

When I click on the 3 vertical dots icon, I get the following pop up menu.

![screenshot_1533632376](https://user-images.githubusercontent.com/8186992/43765811-733ddbd2-9a4e-11e8-80b0-9352d1723a75.png)

But when I use `icon` prop, the app simply crashes

**Comment by prscX** [comment]
Thanks @Cassendra4 for the sharing the requested details.

I have made few changes in order to fix the issue. Can you please upgrade the library to [V0.0.19](https://github.com/prscX/react-native-popover-menu/releases/tag/v0.0.19). 

Please let me know incase you still face the same issue.

Thanks
</ Pranav >

**Comment by shuiRong** [comment]
I got same "crashes". **same code** (with Cassendra4 ) , same behavior.

version:
```
 "react-native-popover-menu": "^0.0.22",
 "react-native-vector-icons": "5.0.0" // I tried to used the latest version too.
```

more info:

Android platform

build.gradle
```
        buildToolsVersion = "28.0.0"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
```
