### ISSUE TITLE
onCancel is not working on Androind

### ISSUE THREAD

**Issue by mickaelw** [prscX/react-native-popover-menu#23]
I'm on RN 0.57 and on 0.0.19 popover menu version.

```
                <TouchableOpacity
                    ref={ref => this.ref = ref}
                    style={styles.missionDeleteIcon}
                    onPress={this.showPopover}
                >
                    <IconFa name={'ellipsis-v'} size={20} />
                </TouchableOpacity>
                <RNPopover
                    visible={this.state.isPopoverVisible}
                    reference={this.ref}
                    onDone={this.onRemove}
                    onCancel={() => alert('alert')}
                >
                    <RNPopover.Menu>
                        <RNPopover.Menu label={'Remove'}/>
                    </RNPopover.Menu>
                </RNPopover>
```

And only on Android the callback onCancel is not trigger when I click outside the popover menu.

**Comment by Shanie1331** [comment]
Same Issue.
@prscX  any updates.

**Comment by hossamnasser938** [comment]
same here

**Comment by thepday12** [comment]
I think @prscX  u need update version of material-popup-menu 2.20  to **3.2.0**.  material-popup-menu support func **setOnDismissListener**  for **MaterialPopupMenu**

**Comment by Unforgiven-wanda** [comment]
Seems this problem persists a year after. Can we still hope for a fix?
Thank you.

**Comment by prscX** [comment]
Thanks @thepday12 for sharing the API and solution.

I have integrated fix and pushed the release. You can now use latest version for the same.

Thanks
</ Pranav >
