### ISSUE TITLE
position of popover appearance is strange in android

### ISSUE THREAD

**Issue by mohanasundaramn** [prscX/react-native-popover-menu#32]
"react": "^16.6.1",
"react-native": "^0.57.5",
"react-native-popover-menu": "0.0.22"

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24430497/50210043-2eb5ee80-039b-11e9-945d-bb5d7a175909.gif)

How do I fix this, I want to show popover on the corresponding button press. I am using the API way.

**Comment by shuiRong** [comment]
@prscX  
so do i (Android)
it seem to happen if it is inside of a list.

**Comment by prscX** [comment]
Thanks for raising the issue.

I believe, it is expected behaviour on Android. Basically the popover is rendered by native library which we have integrated and it is not possible to modify its behaviour.

Thanks
</ Pranav >
