### ISSUE TITLE
RNPopoverMenu.Show must not be null.

### ISSUE THREAD

**Issue by xiaozhongwei** [prscX/react-native-popover-menu#33]
![image](https://user-images.githubusercontent.com/10685005/50479835-7da2fa00-0a13-11e9-8f0d-a612e911edfb.png)

After many attempts and reinstallations, I can't solve this problem.

**Comment by mehdilamrini** [comment]
You have to set a ref to your touchable and pass this ref to your show function like this 
` _show(ref) {
    this.ref = ref
    this.setState({
      menuVisible: true
    });
  }`

` <TouchableOpacity style={styles.treeDotsStyle}  ref={ref => {
          this.ref1 = ref
        }} onPress={() => this._show(this.ref1)}>.....`

This should do the trick!

**Comment by prscX** [comment]
Thanks @xiaozhongwei for raising the issue. Looks like the native library was not linked properly.

I would recommend to upgrade library to latest released version `V1.*` and RN61+ since it has default support for cocoapods.

Thanks
</ Pranav >
