### ISSUE TITLE
Need to implement Onpress event on RNPopover.Menu

### ISSUE THREAD

**Issue by Shanie1331** [prscX/react-native-popover-menu#34]
Please help!!!

<RNPopover.Menu label={"Copy"} icon={copy} />

Need to call function on the above line

**Comment by wsflook** [comment]
man sorry my ignorance, but need one example more details

Exemple:
<Touchable
              background={Touchable.Ripple()}
              onPress={() => this.props.navigation.navigate('Config')}>
              <RNPopover.Menu label={'Config'} />
            </Touchable>

**Comment by prscX** [comment]
@wsflook: You can go through example project for the usage.

@Shanie1331: Closing the issue, since you have found the solution.

Thanks
</ Pranav >
