### ISSUE TITLE
SelectedRowBackgroundColor and Separator Color dont work on iOS

### ISSUE THREAD

**Issue by evanskenobi** [prscX/react-native-popover-menu#38]
Setting selectedRowBackgroundColor and separatorColor props have no effect on the menu color. All the other color props seem to work. I havent tested this module on Android just yet so i cant say if it works or not on that platform

**Comment by mscharl** [comment]
Hey, I couldn't reproduce the `selectedRowBackgroundColor` problem. Maybe it's fixed since this issue is quite old. But I also hab a problem with the `separatorColor` which should be fixed with this #47
