### ISSUE TITLE
Multiple clicks?

### ISSUE THREAD

**Issue by zyasir** [prscX/react-native-popover-menu#42]
Is it possible keep this open and allow multiple presses? I was trying to make a checkbox experience like this:

![](https://thumbs.gfycat.com/OrdinaryFlippantAlbacoretuna-size_restricted.gif)

**Comment by vforvasile** [comment]
Popover menus are usually using a single action. What you're trying to achieve is a selection, try this [https://github.com/prscX/react-native-selection-menu](https://github.com/prscX/react-native-selection-menu) instead.

**Comment by zyasir** [comment]
Thank you very much @vforvasile!
