### ISSUE TITLE
TypeError:null is not an object(evaluating RNPopoverMenu.Show)

### ISSUE THREAD

**Issue by Bruce-Leo-D** [prscX/react-native-popover-menu#44]
I followed the example but it appeared this error message,The project is built by react-native init  
"react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-popover-menu": "^1.0.1",
    "react-native-reanimated": "^1.4.0",
    "react-native-tab-view": "^2.11.0",
    "react-native-vector-icons": "^6.6.0"
How should i fix it

**Comment by dnnetroc** [comment]
How you fixed this bug? @wuse1121
