### ISSUE TITLE
Invariant Violation: No callback found with cbID 5403 and callID 2701 for  RNPopoverMenu.Show - most likely the callback was already invoked. Args: '[]'

### ISSUE THREAD

**Issue by sagar-chhatrola** [prscX/react-native-popover-menu#46]
I am facing this error only on android, when press on menu label. Does anyone getting like this ?
If anyone have solution, please help me.
![WhatsApp Image 2019-12-28 at 6 04 08 PM](https://user-images.githubusercontent.com/25894991/71543745-a5b59800-299c-11ea-8ea1-7547319ae1e2.jpeg)

**Comment by prscX** [comment]
@sagar-chhatrola: Could you please share software stack and the code snippet.

Thanks
</ Pranav >

**Comment by drummerpva** [comment]
I'm having the same problem and I'm using "React Way" with a functional component, Callback onCancel is ok but Callback onDone shows error `... RNPopoverMenu.Show - most likely the callback was already invoked. Args:'[]'`, please check my code please ...
`<PopoverMenu
        visible={openMenu.open}
        reference={openMenu.ref}
        onDone={(mainMenuSelection, subMenuSelection) => {
          console.log('mainMenuSelection', mainMenuSelection);
          console.log('subMenuSelection', subMenuSelection);
        }}
        onCancel={() => {
          console.log('onCancel');
        }}>
        <PopoverMenu.Menu label="Test">
          <PopoverMenu.Menu label="Copy" />
          <PopoverMenu.Menu label="Cut" />
        </PopoverMenu.Menu>
        <PopoverMenu.Menu>
          <PopoverMenu.Menu label="Other Test" />
        </PopoverMenu.Menu>
      </PopoverMenu>`

**Comment by dayaki** [comment]
@sagar-chhatrola @drummerpva any solution? I am facing same problem. @prscX any help?

**Comment by prscX** [comment]
Could you try the same using static API's and also please share the library version you are using.

**Comment by drummerpva** [comment]
@dayaki nothing, i gave up using and implemented my system without popover

**Comment by dayaki** [comment]
> Could you try the same using static API's and also please share the library version you are using.

I am using the API version and library version is 1.0.3

**Comment by prscX** [comment]
@dayaki: I have checked the issue. It might take sometime to get the right fix in place.

But for now you can comment out below line under `react-native-popover-menu/android/src/main/java/ui/popovermenu/RNPopoverMenuModule.java`

Line 189: `menu.setOnDismissListener(onCancelCallback);`. Doing this cancel callback will not be invoked, thats the side effect.

I will update once I have a fix in place.

Thanks
</ Pranav >

**Comment by dayaki** [comment]
@prscX Thanks, that solves it.

**Comment by prscX** [comment]
`onCancel` was not supported on Android. I have removed `onCancel` prop and pushed a V2.* release with few other changes. Please follow `README` for the installation steps.

Thanks
</ Pranav >
