### ISSUE TITLE
Error: Invariant Violation: No callback found with cbID 5403 and callID * for RNPopoverMenu.Show - most likely the callback was already invoked. Args: '[]'

### ISSUE THREAD

**Issue by drummerpva** [prscX/react-native-popover-menu#49]
I'm having the problem with a functional component, Callback onCancel is ok but Callback onDone shows error ... RNPopoverMenu.Show - most likely the callback was already invoked. Args:'[]'
`<PopoverMenu 
  visible={openMenu.open} 
  reference={openMenu.ref} 
  onDone={(mainMenuSelection, subMenuSelection) => { console.log('mainMenuSelection', 
    mainMenuSelection); console.log('subMenuSelection', subMenuSelection); }} 
  onCancel={() => { console.log('onCancel'); }}> 
  <PopoverMenu.Menu label="Test"> 
       <PopoverMenu.Menu label="Copy" /> 
       <PopoverMenu.Menu label="Cut" /> 
  </PopoverMenu.Menu> 
  <PopoverMenu.Menu> 
       <PopoverMenu.Menu label="Other Test" /> 
  </PopoverMenu.Menu>
</PopoverMenu>

RN: 0.61.5
AVD: Android 9
I haven't tested on iOS
I have not tested on class components
Can someone help me?

**Comment by prscX** [comment]
I have checked the issue. It might take sometime to get the right fix in place.

But for now you can comment out below line under `react-native-popover-menu/android/src/main/java/ui/popovermenu/RNPopoverMenuModule.java`

Line 189: `menu.setOnDismissListener(onCancelCallback);`. Doing this cancel callback will not be invoked, thats the side effect.

I will update once I have a fix in place.

Thanks
</ Pranav >

**Comment by prscX** [comment]
`onCancel` was not supported on Android. I have removed `onCancel` prop and pushed a V2.* release with few other changes. Please follow `README` for the installation steps.

Thanks
</ Pranav >
