### ISSUE TITLE
[Android] selection index onDone doesn't count the submenu-items

### ISSUE THREAD

**Issue by danielang** [prscX/react-native-popover-menu#6]
If you open a menu with subitems like the menu of your example, then the selection index in the onDone-callback is alway the index of the parent menu (which holds the submenus)

**Comment by cinder92** [comment]
same issue here

**Comment by cinder92** [comment]
@danielang open file `RNPopoverMenuModule.java` then replace line `130` for 

`onDone.invoke(menuIndex, menuIndex);`

it works for me :)

**Comment by danielang** [comment]
Hey @cinder92 thank you for your hint 🙂 
Your solution has one problem: It will not work if you have more then one root-menu. Like this:
```javascript
let menusAndroid = [
    {
        label: "Editing",
        menus: [
            {
                label: "Copy",
            },
            {
                label: "Paste",
            }
        ]
    },
    {
          label: "Other",
          menus: [
              {
                  label: "Share"
              }
          ]
    },
]
```

I've now toke a look in the code and see that @prscX has forgotten to pass trough the `menuIndex` on JS-side. My PR #8 will fix this.
